/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UpdatePet': ApiRouteHandler<{ name?: string; species?: 'dog' | 'cat' | 'bird' | 'other'; ageMonths?: unknown; status?: 'new' | 'in_quarantine' | 'healthy' | 'available' | 'pending' | 'adopted' | 'ill' | 'under_treatment' | 'recovered' | 'deleted'; notes?: string; nextFeedingAt?: number }, unknown, { topic: 'lc.pet.status.update.requested'; data: { petId: string; event: 'pet.created' | 'feeding.reminder.completed' | 'status.update.requested'; requestedStatus: 'new' | 'in_quarantine' | 'healthy' | 'available' | 'pending' | 'adopted' | 'ill' | 'under_treatment' | 'recovered' | 'deleted'; automatic: boolean } }>
    'SetNextFeedingReminder': EventHandler<{ petId: string; enqueuedAt: number }, { topic: 'lc.feeding.reminder.completed'; data: { petId: string; event: 'pet.created' | 'feeding.reminder.completed' | 'status.update.requested'; requestedStatus: 'new' | 'in_quarantine' | 'healthy' | 'available' | 'pending' | 'adopted' | 'ill' | 'under_treatment' | 'recovered' | 'deleted'; automatic: boolean } }>
    'GetPet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'PetLifecycleOrchestrator': EventHandler<{ petId: string; event: 'pet.created' | 'feeding.reminder.completed' | 'status.update.requested'; requestedStatus: 'new' | 'in_quarantine' | 'healthy' | 'available' | 'pending' | 'adopted' | 'ill' | 'under_treatment' | 'recovered' | 'deleted'; automatic: boolean }, never>
    'GetPets': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeletionReaper': CronHandler<never>
    'DeletePet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreatePet': ApiRouteHandler<{ name: string; species: 'dog' | 'cat' | 'bird' | 'other'; ageMonths: unknown }, unknown, { topic: 'feeding-reminder.enqueued'; data: { petId: string; enqueuedAt: number } } | { topic: 'lc.pet.created'; data: { petId: string; event: 'pet.created' | 'feeding.reminder.completed' | 'status.update.requested'; requestedStatus: 'new' | 'in_quarantine' | 'healthy' | 'available' | 'pending' | 'adopted' | 'ill' | 'under_treatment' | 'recovered' | 'deleted'; automatic: boolean } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
}