/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UpdatePet': ApiRouteHandler<{ name?: string; status?: 'available' | 'pending' | 'adopted'; ageMonths?: unknown }, unknown, never>
    'GetPet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetPets': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeletePet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreatePet': ApiRouteHandler<{ name: string; species: 'dog' | 'cat' | 'bird' | 'other'; ageMonths: unknown }, unknown, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
}