import {
  Model,
  InferAttributes,
  InferCreationAttributes,
  CreationOptional,
  HasOneGetAssociationMixin,
  HasOneCreateAssociationMixin,
  HasManyGetAssociationsMixin,
  HasManyCreateAssociationMixin,
  DataTypes,
} from "sequelize";
import { sequelize } from "../config/database";
import { v7 as uuid7 } from "uuid";

import { Work } from "./work";
import { Cart } from "./cart";
import { Order } from "./order";
import { type MixinTime } from "./base";

export type UserType = MixinTime & {
  id: string;
  name: string;
  password: string;
  email: string;
};

export class User extends Model<
  InferAttributes<User>,
  InferCreationAttributes<User>
> {
  declare id: CreationOptional<string>;
  declare name: string;
  declare password: string;
  declare email: string;

  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare getWorks: HasManyGetAssociationsMixin<Work>;
  declare createWork: HasManyCreateAssociationMixin<Work>;
  declare getCart: HasOneGetAssociationMixin<Cart>;
  declare createCart: HasOneCreateAssociationMixin<Cart>;
  declare createOrder: HasManyCreateAssociationMixin<Order>;
  declare getOrders: HasManyGetAssociationsMixin<Order>;
}

User.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: uuid7,
      primaryKey: true,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: DataTypes.DATE,
    updatedAt: DataTypes.DATE,
  },
  {
    tableName: "users",
    sequelize,
  }
);

// export const User = sequelize.define("user", {
//   id: {
//     type: DataTypes.CHAR(36),
//     primaryKey: true,
//     allowNull: false,
//   },
//   name: {
//     type: DataTypes.STRING,
//     allowNull: false,
//   },
//   password: {
//     type: DataTypes.STRING,
//     allowNull: false,
//   },
//   email: {
//     type: DataTypes.STRING,
//     allowNull: false,
//   },
//   // [INFO] Auto generated by Sequelize
//   // createdAt: {
//   //   type: DataTypes.DATE,
//   //   defaultValue: DataTypes.NOW,
//   // },
//   // updatedAt: {
//   //   type: DataTypes.DATE,
//   //   defaultValue: DataTypes.NOW,
//   //   onUpdate: DataTypes.NOW,
//   // }
// });
