services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: for-ts-node
    volumes:
      - ./db/mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      retries: 10
